"""This file is part of the TPOT library.

TPOT was primarily developed at the University of Pennsylvania by:
    - Randal S. Olson (rso@randalolson.com)
    - Weixuan Fu (weixuanf@upenn.edu)
    - Daniel Angell (dpa34@drexel.edu)
    - and many more generous open source contributors

TPOT is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as
published by the Free Software Foundation, either version 3 of
the License, or (at your option) any later version.

TPOT is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with TPOT. If not, see <http://www.gnu.org/licenses/>.

Scope
-----
Cross-validation generator to be used when covariate adjustments are
needed for the target and it is expected that X contains indicator and
adjY columns as generated by the resAdjTpotPreprocessor script. The number
of splits should equal the number of indicator columns in the training data.

"""

import numpy as np
import pandas as pd

class resAdjPredefinedSplits:
    """Predefined splits based on indicator columns."""

    def __init__(self, n_splits=5, test_size=None, train_size=None, random_state=None):
        self.n_splits = n_splits

    def split(self, X, y=None, groups=None):
        for i in range(self.n_splits):
            col = 'indicator_' + str(i+1)
            if col not in X.columns:
                raise ValueError('X is missing column ' + col)
            train = np.where(X[col]==0)[0]
            test = np.where(X[col]==1)[0]
            yield train, test

    def get_n_splits(self, X, y, groups=None):
        return self.n_splits
